spring.application.name=school
server.port=8080

# Cấu hình Database
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS2025:1433;encrypt=true;trustServerCertificate=true;databaseName=schooldb
spring.datasource.username=sa
spring.datasource.password=123123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cấu hình JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# --- PHẦN QUAN TRỌNG: SỬA LỖI CHỮ TIẾNG VIỆT ---
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
# ----------------------------------------------